CodeRushWithSSAFY/CodeRush

- FEB2_WEEK/나무수확/cheesecrust.java
- **나무 수확**: 
- **https://softeer.ai/practice/7369**: 
초기에는 현재 위치 기반 가장 큰값으로 dp를 수행했지만, 뒤에 값에 따라서 최적 경로가 변경 될 수 있습니다.
따라서 각 위치에서 스프링 쿨러를 설치한 경우의 배열과 설치 하지 않은 경우의 배열을 따로 관리하여 최대값을 구해야 합니다.
> [2주차] 나무수확 - 정연수

- FEB2_WEEK/슈퍼컴퓨터 클러스터/이수빈.java
- **문제 이름**: 슈퍼컴퓨터 클러스터 
- **문제 링크**: https://softeer.ai/practice/6252
실행시간 : 0.266초 
메모리 22.76MB
구해야 할 최소 컴퓨터 성능으로 이분 탐색을 진행했습니다.
19번째 줄을 빼면 틀렸다고 뜨더라구요. 아마 오버플로우 때문일 것 같긴한데 정확하게는 모르겠습니다 ㅎㅎ 조심하시길..
> [2주차] 슈퍼컴퓨터 클러스터 - 이수빈

- FEB2_WEEK/나무섭지/cheesecrust.java
- **나무섭지**: 
- **https://softeer.ai/app/assessment/index.html?xid=424071&xsrfToken=gD2myPk4lbo5ECx3TJCjATGnJPr6FcKo&testType=practice**: 
bfs로 최단 얼마나 걸리는 지 탐색과 유령이 얼마만에 도달 가능한지 계산.
**이때 bfs 의 방문체크는 nxt 만든 후 nxt 에 대해서 하는 것이 좋음 현재에서 하는거랑 별 차이 안나는줄 알앗는데 많이남.**
> [2주차] 나무섭지 - 정연수

- FEB2_WEEK/효도음식/cheesecrust.java
- **효도 음식**: 
- **https://softeer.ai/practice/7367**: 
수열에서 연속하는 가장 큰 수를 dp 로 구합니다.
이를 왼쪽과 오른쪽에 수행하여 각각의 범위에서의 최댓값을 구하여 더합니다.
> [2주차] 효도음식 - 정연수

- FEB2_WEEK/효도_음식/이수빈.java
- **문제 이름**: 효도 음식
- **문제 링크**: https://softeer.ai/practice/7367
실행시간 : 0.186초
메모리 : 19.38MB
왼쪽에서부터 인덱스를 증가시키면서 해당 인덱스까지의 최댓값을 leftDp 배열에 저장하고, 오른쪽도 마찬가지로 rightDp 배열에 저장했습니다.
음식은 인접하지 않아야 하기 때문에 `leftDp[i - 1] + rightDp[i + 1]`의 값에 대해 반복문을 돌며 최댓값을 구했습니다.
dp 너무 어려워요..
> [2주차] 효도 음식 - 이수빈

- FEB2_WEEK/효도음식/김준혁.java
- **문제 이름**: 효도 음식
- **문제 링크**: https://softeer.ai/practice/7367
- 실행 시간 : 0.178초
- 메모리 : 19.01MB
- ingredNum : 주어진 재료 개수
- pivot : 각 요리에 쓰일 재료묶음을 나누는 경계 재료 인덱스
1. 왼쪽 : 인덱스 0 부터 ingredNum-3까지, 각 인덱스까지의 최대 부분배열 합을 기록
2. 오른쪽 : 왼쪽과 같은 방법으로 배열 끝부터 인덱스 2까지 최대 부분배열 합을 기록
3. pivot을 인덱스 1 부터 ingredNum-2까지 옮겨가면서, 나누어진 왼쪽/오른쪽 부분 배열의 최대 합끼리 더하기
4. 가장 큰 값을 출력
방법을 모르겠어서 한슬누나 pr 보고 카데인 알고리즘이라는게 있다는 걸 알아서 어떤 알고리즘인지 공부하고 풀었습니다.
풀긴 풀었는데 명확하게 설명하기가 어렵네요.. 조금 더 생각을 해봐야 할 것 같습니다 ㅠㅠ
> [2주차] 효도 음식 - 김준혁

- FEB2_WEEK/징검다리/김준혁.java
- **문제 이름**: 징검다리
- **문제 링크**: https://softeer.ai/practice/6293
- 실행 시간 : 0.123초
- 메모리 : 11.07MB
1. 입력받은 바위 개수 크기의 배열 2개 생성
- int[ ] rocks : 바위 높이 저장할 배열
- int[ ] lengths : 시작 위치부터 특정 위치의 바위까지의 최장 순열 길이 저장 배열
1. 입력받은 바위 배열 순회
2. 현재 위치의 오른쪽 바위들을 순회 
2-1. 현재 위치보다 높은 바위 발견하면 (현재 위치까지의 최장 순열 길이 + 1) 와 (높은 바위의 현재 최장 순열 길이) 중 더 큰 값 선택 => 높은 바위의 현재 최장 순열 길이로 결정
2-2. if ( rocks[ i ] < rocks[ j ])  lengths[ j ] = max(lengths[ j ], lengths[ i ] + 1)
3. 순회하면서 최댓값 추적하기
4. 정답 출력
4-1. 배열 lengths는 모든 값이 0으로 초기화 되어있으므로 실제 순열의 길이는 lengths의 값보다 1이 크다
4-2. 따라서 추적한 최댓값 + 1 이 정답
> [2주차] 징검다리 - 김준혁 

- FEB2_WEEK/나무섭지/이수빈.java
- **문제 이름**: 나무 섭지
- **문제 링크**: https://softeer.ai/practice/7726
실행 시간 : 0.202초
메모리 : 18.88MB
bfs를 이용하여 남우가 출구까지 갈 수 있는 최단 거리를 구합니다.
유령들의 좌표를 리스트에 저장 후, 출구까지의 최단 거리를 구합니다.
남우의 최단 거리보다 유령들의 최단 거리가 더 짧은 경우 남우가 유령에게 잡히기 때문에 No를 출력합니다.
오타 조심하기~
> [2주차] 나무섭지 - 이수빈

- FEB2_WEEK/나무섭지/김준혁.java
- **문제 이름**: 나무섭지
- **문제 링크**: https://softeer.ai/practice/7726
- 실행 시간 : 0.218초
- 메모리 : 20.27MB 
**" 남우의 최소 탈출구 도달 시간보다 짧은 시간 안에 탈출구에 도달 가능한 유령이 있다면, 유령은 남우를 잡을 수 있음 "**
minGhost : 유령의 최소 탈출구 도달 시간
minNam : 남우의 최소 탈출구 도달 시간
조건1 : minGhost <= minNam 
- 위 조건을 만족하면, 남우가 다른 경로로 가더라도 유령은 남우를 잡을 수 있음 (탈출구에서 대기)
조건2 : minGhost > minNam 
- **가정 : 유령이 남우를 잡을 수 있음**
- 중간에 유령이 남우를 잡는다(즉, 같은 시점에 한 칸에 유령과 남우가 함께 존재할 수 있다)면, 유령은 최소 남우와 같은 시간에 탈출구 도달이 가능함 => 남우의 최단경로일때도 마찬가지!
- 이 경우 "minGhost > minNam" 은 참일 수 없음
- 따라서 가정인 "유령이 남우를 잡을 수 있다" 는 거짓
- 즉, minGhost > minNam 이면 유령은 남우를 잡을 수 없음
**따라서 유령의 최소 탈출구 도달 시간과 남우의 최소 탈출구 도달 시간을 비교하여 탈출 가능 여부 판단이 가능함**
탈출구까지 도달 가능한 최소 시간을 유령과 남우 각각 계산
1. 유령 : 유령의 위치와 출구 위치의 좌표값 차이로 계산 -> …
> [2주차] 나무섭지 - 김준혁

- FEB2_WEEK/효도음식/정한슬.java
- **문제 이름**: 
- **문제 링크**: 
첫번째 메뉴는 앞->뒤/ 두번째 메뉴는 뒤->앞으로 만드는데 이때 카데인 알고리즘으로 여태까지 연속으로 합할 건지, 아니면 현재 값으로만 다시 시작할지 정합니다. 더불어 이전에 가장 큰값들을 저장해놔서(firstMenu[], secondMenu[])  그 카데인 값과 비교해서 큰값을 유지합니다.
코드에 최대한 자세히 썼습니다,,
음.. 자꾸 빈 공간 idx에 집착해서 그 인덱스를 기준으로 나눈 좌/우 배열의 최대값을 찾으려고 했습니다..
그러다보니 이중포문으로밖에 생각이 안되서 시간초과가 났고 카데인 알고리즘도 제대로 안쓴것 같아서 이해하는데 한참 걸렸습니다 ㅠ,,ㅠ
> [2주차] 효도 음식 - 정한슬

- FEB2_WEEK/나무수확/정한슬.java
- **문제 이름**: 나무 수확
- **문제 링크**:  https://softeer.ai/practice/7369
bfs로 되면 참 좋겠지만 안되서 dp개념을 사용했어야했습니다. 
어차피 방향은 2가지 밖에 없으니 오른쪽, 왼쪽에서 오는 최대 value값과 최대 sum값을 통해 어떤 경로로 가는 것이 이득인지 선택합니다.
* 오른쪽 maxSum > 왼쪽 maxSum인 경우 오른쪽의 maxValue와 현재 board의 값 두개를 비교해서 maxValue를 갱신 합니다.
* 오른쪽 maxSum < 왼쪽 maxSum인 경우 왼쪽의 maxValue와 현재 board의 값 두개를 비교해서 maxValue를 갱신 합니다.
* 오른쪽 maxSum == 왼쪽 maxSum인 경우 왼쪽의 maxValue와 오른쪽의 maxValue와 현재 board의 값 모두 비교하여 maxValue를 갱신 합니다.
maxSum은 현재 board 값을 더해 갱신한 뒤 현재 row, col에서의 dp를 기록합니다.
* 이 부분에서 우리는 최종 maxSum을 구할 수 있습니다.
* 단 이전 처럼 maxValue와 maxSum을 따로 비교하면 maxSum은 오른쪽 값이 더 큰데 maxValue는 위쪽에서 온 값으로 갱신되어 최종적으로 maxSum + maxValue + board[row][col] 했을 때 잘 못된 값이 나올 수 있습니다.
* 그래서 maxFruitSum 자체를 여태까지의 maxSum …
> [2주차] 나무 수확 - 정한슬

- FEB2_WEEK/함께하는효도/정한슬.java
- **문제 이름**:  함께하는 효도
- **문제 링크**: https://softeer.ai/practice/7727
n <= 20, 이므로 완전 탐색 가능 -> 각 친구들마다 완전 탐색 dfs를 해서 열매 수확량의 최대 합을 구하자
처음 위치에서 0초부터 열매를 수확 할 수 있다.
단, 처음 위치에서 진행 중에 친구들의 경로는 겹칠 수 있다. 
겹친 경우 (싸워서 이긴) 사람이 그 열매를 수확할 수 있다. (진 사람은 열매 수확 X)
> [2주차] 함께하는 효도 - 정한슬

- FEB_WEEK2/나무섭지/정한슬.java
- **문제 이름**:  나무섭지
- **문제 링크**:  https://softeer.ai/practice/7726/history?questionType=ALGORITHM
dfs... 그리고 벽 뚫는 개념이면 bfs굳이 안하고 좌표 값으로 거리 찾기...
.. 다른분들 코드와 설명으로 간신히 풀었습니다.. 다시 풀라고하면 못풀듯...
> [2주차] 나무섭지 -정한슬

- FEB_WEEK2/슈퍼컴퓨터_클러스터/정한슬.java
- **문제 이름**:  슈퍼컴퓨터 클러스터
- **문제 링크**: https://softeer.ai/practice/6252
이분 탐색으로 풀었습니다. 
목요일에 풀이법 야무지게 들었는데도 시간초과 + 답 틀림 : ) 
변수명 영어로만 짓는거 넘 힘들어서 한글 썼습니다,,
> [2주차] 슈퍼컴퓨터 클러스터 - 정한슬

- FEB_WEEK1/좌석관리/cheesecrust.java
- **좌석 관리**: 
- **https://softeer.ai/practice/6267**: 
빡구현 입니다. 전체 사원 배열을 만드려 하지 말고 들어온 사원을 배열에 추가하는 방식으로 구현
설계를 정확히 하고 해야 소요시간을 줄일 수 있습니다.
> [1주차 보충] 좌석 관리 - 정연수

- FEB_WEEK3/달팽이_숫자/정연수.java
- **달팽이**: 
- **https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV5PobmqAPoDFAUq**: 
부딪히면 방향을 꺽습니다.
> [3주차] 달팽이 - 정연수

- FEB_WEEK2/슈퍼컴퓨터_클러스터/cheesecrust.java
- **슈퍼컴퓨터**: 
- **https://softeer.ai/practice/6252**: 
이분 탐색
탐색해야하는 양이 많아서 이분탐색으로 접근해야합니다. 
세션때 팀원분들의 알려주셔서 삽질을 줄 일 수 있었습니다.
Java에서 배열의 크기와 인덱스는 반드시 int 타입이어야 하는 사실을 새로 알게 되었습니다.
다음부터는 이 또한 유의하며 풀면 좋을것 같습ㄴ다.
> [2주차] 슈퍼컴퓨터 - 정연수

- FEB_WEEK3/달팽이_숫자/박재환.java
- FEB_WEEK3/로드_밸런서_트래픽_예측/박재환.java
- **문제 이름**: 1954. 달팽이 숫자
- **문제 링크**: https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV5PobmqAPoDFAUq
숫자가 채워지는 방향은 
오른쪽 -> 아래 -> 왼쪽 -> 위 
방향으로 숫자가 1부터 mapSize^2 만큼 채워지게 됩니다. 이때 방문처리 를 통하여 특정 방향으로 이동하다가, 이미 처리한 위치이거나, 범위를 벗어나는 경우 방향을 전환시켜주며 서서히 안쪽으로 숫자를 채워나가는 방식으로 해결하였습니다.
지난 월말평가에서 나왔던 문제로 단순해보이지만 막상 실제로 구현하려니 막막했던 기억이 있습니다. 운이 좋게 반대로 하면 어떨까 라는 생각이 들어 아이디어를 생각해 낼 수 있었습니다.
> [3주차] 달팽이 숫자 - 박재환

- FEB_WEEK2/함께_하는_효도/이수빈.java
- **문제 이름**: 함께하는 효도
- **문제 링크**: https://softeer.ai/practice/7727
실행 시간 : 0.108초
메모리 : 11.86MB
각 좌표에서 0,1,2,3 초 일때 방문했는지 체크하기 위한 3차원 visitedTime[row][col][time] 배열을 만들어 dfs를 진행했습니다.
> [2주차] 함께하는 효도 - 이수빈

- FEB_WEEK3/좌석_관리/이수빈.java
- **문제 이름**: 좌석 관리
- **문제 링크**: https://softeer.ai/practice/6267
실행 시간 : 0.634초
메모리 : 28.49MB
그냥 열심히 구현했습니다!!
사원 수가 10000명인데 배열을 1000으로 잡고 해서 런타임에러가 계속 났습니다.. 이걸로 한시간 뻘짓했어요 ㅠㅠ 문제 잘읽기 중요
> [3주차] 좌석 관리 - 이수빈

- FEB_WEEK3/자동차_테스트/이수빈.java
- **문제 이름**: 자동차 테스트
- **문제 링크**: https://softeer.ai/practice/6247
실행 시간 : 1.323초
메모리 : 62.33MB
50,000 * 200,000 은 시간 초과이기 때문에
자동차 배열에서 목표 중앙값을 가진 차를 찾기 위한 방법으로 이분 탐색을 사용하였습니다.
> [3주차] 자동차 테스트 - 이수빈

- FEB_WEEK3/달팽이_숫자/이수빈.java
- **문제 이름**: 달팽이 숫자
- **문제 링크**: 
실행 시간 : 83ms
메모리 : 25,216kb
0,0에서 시작하여 우, 하, 좌, 상 순서대로 갈 곳이 없으면 방향을 바꿔주었습니다.
재귀로 구현하였습니다.
오늘 실습 문제랑 같아서 좋네요~ ㅎㅎ
> [3주차] 달팽이 숫자 - 이수빈

- FEB_WEEK3/거리합_구하기/이수빈.java
- **문제 이름**: 거리합 구하기
- **문제 링크**: https://softeer.ai/practice/6258
실행 시간 : 1.721초
메모리 : 97.95MB
1번 노드를 루트로 둔 상태에서 각 노드들의 서브트리 노드 개수와 거리합을 구해줍니다. (바텀업)
1번 노드부터 아래로 내려오면서 (탑다운) 자식노드들을 루트로 만들어 거리합을 계산해줍니다.
재환님 코드를 아주 열심히 공부했습니다................ 너무어려우어요 이거 어케풀죠?.....
> [3주차] 거리합 구하기 - 이수빈

- FEB_WEEK3/달팽이_숫자/정한슬.java
- **문제 이름**: 1954. 달팽이 숫자
- **문제 링크**: https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV5PobmqAPoDFAUq
0,0부터 반복되는 순서로 방향 전환을 해주며 board를 채워줍니다.
이번주 문제 난이도 조절 대실패였는데 달팽이가 있어서 얼~마나 다행이었는지 몰라요~
저는 월말평가 못풀고 index 에러 나서 그것도 해결하고 싶었는 데 일단 못하고 제출합니다..
그리고 왜 sb로 하려고 한 부분으로 하면 fail되는지 모르겠어요,, 뭔가 제가 잘못한거겠지만,,? 출력문제니까 걍 포기했습니다.
> [3주차] 달팽이 숫자 - 정한슬

- FEB_WEEK3/좌석_관리/정한슬.java
- Thanks to cheese crust ...
- **문제 이름**:  좌석 관리
- **문제 링크**:  https://softeer.ai/practice/6267
연수님 덕에 풀 수 있었습니다.. 개인적으로 직관적인건 클래스라고 생각하지만 배열로 풀고싶어서 저는 배열로 넣었습니다.
스터디 덕에 풀 수 있었던 것 같아요 ..
> [3주차] 좌석 관리 - 정한슬

- FEB_WEEK3/자동차_테스트/정한슬.java
- **문제 이름**: 자동차 테스트
- **문제 링크**: https://softeer.ai/practice/6247
연비를 오름차순으로 정렬을 한뒤 만들고 싶은 중앙값이 아예 없거나, 첫번째에 있거나 맨 마지막에 있으면 중앙값을 만들 수 없기에 바로 0으로 return 하도록 처리했습니다.  없는 걸 빠르게 판단하기 위해서 Arrays.binarySearch(array, 원하는 value) = idx 메서드를 사용했습니다. 그리고 첫번째, 맨 마지막이 아닌 idx에서는 앞/뒤로 원하는 중앙값을 만들 수 있는 작은값들 /큰값들의 경우의 수이기 때문에 곱하기로 return 했습니다.
음.. 저 메서드가 코테때 생각이 날런지,, ,, .. 이렇게 푸는게 맞는건진 모르겠습니당
> [3주차] 자동차 테스트 - 정한슬

- FEB_WEEK3/자동차_테스트/김준혁.java
- **문제 이름**: 자동차 테스트
- **문제 링크**: https://softeer.ai/practice/6247
- 실행 시간 : 1.388 초
- 메모리 : 58.06MB
타겟 중앙값의 경우의 수 : (더 작은 값 개수) * (더 큰 값 개수)
- **결국 더 작은 값과 더 큰 값을 어떻게 셀 것인지가 관건**
- 이것 저것 여러번 시도해봤는데, 결국 차 배열을 오름차순 정렬하고 인덱스를 가지고 알아내는게 가장 빨랐다
- 정렬만 끝나면 인덱스로 더 작은/더 큰 값을 찾는 것은 아주 간단함
- n의 값도 최대 50,000으로 엄청 크지는 않아서 정렬하는데에 시간이 많이 안 들었나 봄
연비의 최대값이 10억으로 엄청 커서 전체적으로 int 대신 long타입을 사용했습니다. 그런데 이게 안익숙해서 에러가 많이 나더라구요.
그래서 gpt랑 대화하면서 알게된 사실들을 정리해보겠습니다.
에러 1 : ++ 연산자는 기본형 타입에만 사용 가능
에러 2 : 배열 생성할때, new Type [ size ] 에서 size는 무조건 int여야함. Long이면 안됨
- 이유 : **배열의 크기는 int 범위인 약 21억개 이상을 초과할수 없기 때문에**
- 그 이상의 범위가 필요하다면 List같은 동적 자료구조를 사용해야 함
- 이거 알고 계셨나요...? 일단 저는 처음 알았습니다..
> [3주차] 자동차 테스트 - 김준혁

- FEB_WEEK4/문자열_옮기기/정한슬.java
- **문제 이름**: 문자열 옮기기
- **문제 링크**: https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AZPOBiaqNo8DFAWB
문제가 시키는대로 totalShift값이 양수인지 음수인지의 따라 문자열을 옮겼습니다!
바뀌는 횟수를 담을 totalShift를 int형으로 해서 자꾸 틀렸었습니다,, 하하하
> [4주차] 문자열 옮기기 - 정한슬

- FEB_WEEK4/차세대_지능형_교통시스템/정한슬.java
- **문제 이름**:  차세대 지능형 교통 시스템
- **문제 링크**:  https://softeer.ai/practice/6274
처음에는 차량의 접근 방향을 생각하지않고 교통 신호만 적용했었고 차량 접근방향을 생각하니 어디서 카운트를 줘야할지 헷갈렸었습니다..! 결국 접근할때 도착은 바로 카운트를 하되 접근 방향과 해당 신호와의 접근 방향이 다르면 다음 신호로 못가도록 pass 해줬어야 했습니다.
실습 문제와 병행하니 4주차는 너무 힘들었습니다,,
> [4주차] 차세대 지능형 교통 시스템 - 정한슬

- FEB_WEEK4/Phi_Squared/정한슬.java
- **문제 이름**: [한양대 HCPC 2023] Phi Squared
- **문제 링크**: https://softeer.ai/practice/7697
처음에는 linked list 자료구조에서 미생물이 흡수 당한 경우 해당 미생물을 remove했었는데 시간초과가 나서 다음날 흡수를 진행시킬 자료구조를 하나 더 추가해서 풀이하는 방법을 택했습니다. 근데 제가 풀이한건 다음과 같은데 이건 틀리고 커밋한 코드는 맞다는데 대체 뭐가 다른지 모르겠습니다
```java
import java.io.*;
import java.util.*;
/*
N: 미생물들의 수 -> microCount
a1 a2 a3 ... 이 있을 때 a1이 a2보다 작으면 a2에 흡수된다.
흡수되는 과정은 인접한 미생물에서만 가능하고 차례대로 진행된다.
작거나 같을 때 흡수됨!
(1, 4) (2, 1) (3, 3) (4, 2) (5, 5)일때,
1일차
(1, 4) 랑 (2, 1) 인접한 두개를 비교했을 때 idx: 1이 크다. 흡수 -> (1, 5)
(1, 5) (3, 3) (4, 2) 1은 이미 흡수했으니까 pass 하고 (3, 3) (4, 2) 비교했을 때 idx:3이 크다. 흡수 -> (3, 5)
(3, 5) (5, 5) 3도 흡수 했으니 pass 하고 idx 5 입장에서 3과 같기 때문에 흡수 가능하다. 흡수 -> (5, 10)
2일차
(1, 5) (5, 10)
idx 1은 idx 5보다 …
```
> [4주차] Phi Squared - 정한슬

- FEB_WEEK4/마이크로서버/박재환.java
- **문제 이름**: 마이크로서버
- **문제 링크**: https://softeer.ai/practice/6264
특별한 알고리즘 없이 Greedy 와 투포인터를 이용한 풀이방법을 사용했습니다. 
가장 먼저 대기중인 서비스를 오름차순으로 정렬하여, 사전에 묶을 수 있는 업무를 묶는 전처리 과정을 거쳤습니다.
이후 투포인터를 사용하여 최소값과, 최대값을 묶어 서버를 할당해주었습니다.
https://school.programmers.co.kr/learn/courses/30/lessons/42885
위에 해당하는 문제를 풀어본 기억이 있어 같은 풀이법을 적용하였고, 조금 더 응용하여 해결했습니다!
해당 문제가 어려우시다면 위 링크 문제 한 번 풀어보시면 좋을거같습니다!
> [4주차] 마이크서버 - 박재환

- FEB_WEEK3/Phi_Squared/박재환.java
- FEB_WEEK4/문자열_옮기기/박재환.java
- FEB_WEEK4/출퇴근길/박재환.java
- **문제 이름**: 출퇴근길
- **문제 링크**: https://softeer.ai/practice/6248
문제에서 요구하는 정답은 출근길, 퇴근길에 모두 방문할 수 있는 노드의 수를 구하는 것이였습니다.
따라서 DFS 를 사용해 집 -> 회사, 회사 -> 집 의 경로를 확인해주었습니다. 하지만 조금 다른 개념이 하나 포함되었습니다.
**집 -> 중간 노드들 -> 회사** 혹은 **집 -> 중간 노드들 -> 집** 
이는 곳 출발지에서 중간 노드로 이동이 가능한지 + 중간 노드에서 목적지로 이동이 가능한지를 구별해야 했습니다. 
따라서 정방향 그래프와 역방향 그래프를 사용하여 출발지에서 이동 가능한 노드들을 확인 후, 역방향 그래프를 사용해 목적지까지 이동이 가능한 중간 노드들을 찾아주었습니다.
말이 조금 어려운데 주석에 더욱 자세하게 써 놓았으니 확인해보시면 좋을거같습니다~!
기저조건 부분에서 좀 헷갈렸습니다. 당연하게 일반적인 DFS 와 동일하게 목적지에 도착하면 탐색을 종료해주었었는데, 일부 테스트 케이스에서 오답이 발생하였습니다. 해당 부분을 확인해보니, 문제에서 사용한 풀이 방법인 모든 사용 노드들을 체크한 배열을 사용해 중복 노드를 구하는 방법에서는 목적지에 도착해서 종료하는 조건이 아닌, 단순하게 탐색 가능한 모든 노드들을 체크해주어야 정확한 중복 처리가 가능하다는 것을 알게되었습니다.
> [4주차] 출퇴근길 - 박재환

- FEB_WEEK3/Phi_Squared/박재환.java
- FEB_WEEK3/달팽이_숫자/박재환.java
- FEB_WEEK3/로드_밸런서_트래픽_예측/박재환.java
- **문제 이름**: [한양대 HCPC 2023] Phi Squared
- **문제 링크**: https://softeer.ai/practice/7697
Queue 와 Stack 의 개념을 활용하여 문제를 해결하였습니다. 
아직 합쳐지기 전의 미생물들을 Queue 에 넣은 뒤, 합치는 작업을 수행하며 Stack 에 삽입하였습니다. 
이때 현재 미생물에서 이전의 미생물의 Stack 에서 확인, 다음 미생물은 Queue 에서 확인하였습니다.
합치는 작업을 수행한 후 다시 Queue 에 넣어줘야하는 작업을 Deque 를 사용하여 따로 pop 연산 없이 참조값으로 전달하여 처리하였습니다.
비슷한지는 잘 모르겠으나 **SWEA** 의 **3000. 중간값 구하기** 문제에서 풀었던 개념이 생각나서 동일하게 적용해보았습니다.
https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV-fO0s6ARoDFAXT
⚠️ int 로 계산하면 문제 틀립니다!!
> [4주차] Phi Squared - 박재환

- FEB_WEEK3/Phi_Squared/박재환.java
- FEB_WEEK4/문자열_옮기기/박재환.java
- **문제 이름**: 문자열 옮기기
- **문제 링크**: https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AZPOBiaqNo8DFAWB
문자열의 특정 문자를 앞 또는 뒤로 이동하는 문제였습니다. StringBuilder 나 StringBuffer 를 사용해서 문제를 풀 수도 있을 것이라 생각합니다. 다만 저는 익숙하지 않아 Deque 를 사용하여 문제를 해결하였습니다. 
각 명령어의 절댓값으로 for 문을 수행하고, for 문 내부에서 양수인지, 음수인지 구분하여 연산을 수행하였습니다.
시간초과가 나는 분들을 위해 한 가지 힌트를 드리자면 문자열을 앞 또는 뒤로 이동시킬때, 특정 횟수가 되면 기존 문자열과 같은 형태가 됩니다. 즉 불필요한 연산 횟수를 제거한다면 시간초과 없이 통과할 수 있습니다.
> [4주차] 문자열 옮기기 - 박재환

- FEB_WEEK4/문자열_옮기기/이수빈.java
- **문제 이름**: 문자열 옮기기
- **문제 링크**: 
실행 시간 : 199ms
메모리 : 27776KB
문자열의 시작 인덱스를 startIdx로 두고 들어오는 명령 숫자를 더해준다.
startIdx가 0보다 작은 경우 문자열길이를 계속 더해줘서 양수를 만들어준다.
startIdx에 문자열 길이를 나머지 연산하여 문자열을 출력한다.
> [4주차] 문자열 옮기기 - 이수빈

- FEB_WEEK4/문자열옮기기/정연수.java
- **문자열 옮기기**: 
- **https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AZPOBiaqNo8DFAWB**: 
초기 arraydeque 로 접근했으나 시간 초과가 나서 한번에 자르는 지점을 계산해서 SUBSTRING으로 잘라서 붙였습니다,
> [4주차] 문자열 옮기기 - 정연수

- FEB_WEEK4/Phi_Squard/정연수.java
- **Phi squard**: 
- **https://softeer.ai/practice/7697**: 
큐에 순서대로 미생물을 넣어 하나씩 빼며 처리했습니다.
> [4주차] Phi_squard - 정연수

- MAR/WEEK2/서버_증설_횟수/정연수.java
- **문제 이름**: 서버증설횟수
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/389479
구현 문제입니다.
> [2주차] 서버증설횟수 - 정연수

- MAR/WEEK1/안전_영역/정연수.java
- **안전영역**: 
- **https://www.acmicpc.net/problem/2468**: 
시간 될때 마다 하나씩 지우면서 빈칸을 채웁니다.
> [1주차] 안전영역 - 정연수

- MAR/WEEK2/캐시/이수빈.java
- **문제 이름**: 캐시
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/17680
큐를 이용하여 풀었습니다
처음에 HashMap, TreeMap, PriorityQueue 별걸 다했는데.... 한슬언니 코드 보니 그냥 큐로 하면 되는 거였네요...바보.......
> [2주차] 캐시 - 이수빈

- MAR/WEEK2/석유_시추/이수빈.java
- **문제 이름**: 석유 시추
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/250136
각 칸에 석유가 있을 때 bfs 실행
bfs 하면서 방문한 col이 어딘지 기록하고 개수를 세줌
bfs가 끝나면 방문한 col에 세준 개수를 더해줌
개수 최댓값 출력
> [2주차] 석유 시추 - 이수빈

- MAR/WEEK2/캐시/정한슬.java
- **문제 이름**: 캐시
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/17680
LRU 페이징 처리대로 arraydeque 사용해서 처리했습니다 ~
> [2주차] 캐시 - 정한슬

- MAR/WEEK2/땅따먹기/이수빈.java
- **문제 이름**: 땅따먹기
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/12913
정수 삼각형과 비슷한 문제입니다! dp로 풀었습니다
> [2주차] 땅따먹기 - 이수빈

- MAR/WEEK2/정수_삼각형/이수빈.java
- **문제 이름**: 정수 삼각형
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/43105?language=java
DP를 이용하여 풀었습니다.
> [2주차] 정수 삼각형 - 이수빈

- MAR/WEEK1/안전_영역/이수빈.java
- **문제 이름**: 안전 영역
- **문제 링크**: https://www.acmicpc.net/problem/2468
메모리 : 32228KB
실행 시간 : 220ms
전체를 bfs로 돌았습니다!
월말평가에선 틀렸습니다... result 초기 값을 0으로 해서 틀렸습니다 ㅠ
> [1주차] 안전 영역 - 이수빈

- MAR/WEEK2/땅따먹기/정한슬.java
- **문제 이름**:  땅따먹기
- **문제 링크**:  https://school.programmers.co.kr/learn/courses/30/lessons/12913
처음엔 queue에 넣어서 브루트포스로 다 비교하고싶었는데 시초, 메모리초과가 나서 dp로 풀이했어요,, dp로 풀이할 때도 greedy마냥 행에서 가장 큰 요소를 더하는 걸로 진행했는데 반례보고 이해했습니다.
> [2주차] 땅따먹기 - 정한슬

- MAR/WEEK1/안전_영역/박재환.java
- **문제 이름**: 안전 영역
- **문제 링크**: https://www.acmicpc.net/problem/2468
나올 수 있는 강수량은 격자에서 주어지는 최소값 ~ 최대값 사이라고 생각을 하였습니다. 
따라서 격자를 입력 받으며 각 최소값과 최대값을 기록하여 탐색 범위를 설정하였습니다. 
탐색은 Queue 를 사용하여 인접 구역을 체크하는 방식으로 구현하였습니다.
업서용~!
> [1주차] 안전 영역 - 박재환

- MAR/WEEK2/정수_삼각형/박재환.java
- **문제 이름**: 정수 삼각형
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/43105
문제를 보자마자 트리의 원리를 이용하면 해결할 수 있을 것 같다는 생각이 들었습니다. 
손으로 그려보던 중 ( i, j ) 번째 노드에서 이동할 수 있는 자식 노드는 ( i+1, j ), ( i+1, j+1 ) 이라는 규칙을 찾을 수 있었고, 
이전에 소프티어에서 풀었던 문제처럼 바텀업으로 접근하면 문제를 해결할 수 있을 것이라 생각하였습니다.
재귀를 통해서도 구현할 수 있지만 이는 누적 합을 저장해놓지 않는다면, 같은 위치를 중복해서 탐색하므로 시간초과가 나게됩니다.
> [2주차] 정수 삼각형 - 박재환

- MAR/WEEK2/땅따먹기/박재환.java
- **문제 이름**: 땅따먹기
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/12913
DP 를 사용하였습니다. 
ROW 를 Idx = 1 부터 탐색하여, 현 위치에서 고를 수 있는 이전 ROW 의 최대 값을 선택하여 O(N) 시간으로 풀었습니다. 
처음엔 재귀적으로 푸는 방법을 생각하였는데, 이는 3^100000 의 시간 복잡도로 시간 초과 날 것으로 예상하여 연산을 줄이는 방향으로 생각하였습니다.
> [2주차] 땅따먹기 - 박재환

- MAR/WEEK3/봉인된_주문/정한슬.java
- **문제 이름**: 봉인된 주문
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/389481
지운 주문을 주문서에 써있는 순으로 sort 한뒤 해당 index를 구한 뒤 찾는 n보다 작으면 지워야하고 크면 상관없으니 break로 뺐습니다. 지운 개수를 세고 나서 n값에 더해 해당 index 값을 가진 주문을 return하면 됩니다. 그냥 알파벳 26개를 통해 26진법으로 생각하면되는데 괜히 헤맸습니다 ㅠ 
접근은 맞게했지만... 뇌가 돌아가지않았습니당 : ㅇ ,,, ...
> [3주차] 봉인된 주문 - 정한슬

- MAR/WEEK3/완전범죄/정한슬.java
- **문제 이름**: 완전 범죄
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/389480
- dp 풀이
- dfs + 메모제이션 풀이
1. 첫 물건부터 끝까지 a가 훔친 값을 totalAMax값으로 저장합니다.
2. 2차원 dp배열을 만들어 dp[length][m] 각 물건마다 b가 최대로 훔쳤다고 가정합니다 -> a가 최소로 훔치게 되는 것
3. 첫 물건을 b가 훔칠수 있는 수량(info[0][1])부터는 b가 훔쳤다고 가정하고 totalAMax - info[0][0]을 빼주어 dp배열에 저장합니다.
4. 첫번째 물건 이후에는 b가 훔칠 수 있는 수량이후부터 b가 훔쳤을때와 b가 훔치지 않았을 때로 min값을 저장합니다 (a가 최소로 훔치게 되는 것)
풀이가 생각이 안나서 저도 풀이 봤는데 저는 이렇게 풀이한 dp가 이해하기 편했습니다.
> [3주차] 완전 범죄 - 정한슬

- MAR/WEEK3/비밀_코드_해독/정한슬.java
- **문제 이름**: 비밀 코드 해독
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/388352
1부터 n까지 5개 조합한 뒤 q에서 맞다는 수랑 같으면 카운트했습니다!
저도 고집부려보려했는데 방법도 생각 안나고... 재환이가 준 힌트가 아른아른 거려서 그렇게 풀었습니다..
> [3주차] 비밀 코드 해독 - 정한슬

- MAR/WEEK3/봉인된_주문/이수빈.java
- **문제 이름**: 봉인된 주문
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/389481
1. 제거해야 할 단어를 사전순으로 정렬
2. 각 자릿수 별로 나올 수 있는 단어 수를 구하고, 제거해야 할 단어들의 길이를 확인하며 수를 빼준다.
3. 단어를 제거하지 않았을 때 n이 원래 몇번째인지 구해준다. (originalN)
4. n번째 단어의 길이를 구한다.
5. n번째 단어 길이의 시작 단어 (예를 들어 길이가 4이면 aaaa)가 몇번째인지 구한다.
6. dfs
6-1. 단어를 첫 글자부터 생성.
6-2. 현재 글자의 뒷부분에서 나올 수 있는 경우의 수를 다 구하고 그게 originalN보다 작다면 dfs
6-3. 기저조건은 단어 길이가 n번째 단어의 길이가 되었을 때
저 좀 많이 복잡하게 푼 것 같습니다.......... 다른 분들 코드 보니 되게 간단하네여....
> [3주차] 봉인된 주문 - 이수빈

- MAR/WEEK3/지게차와_크레인/이수빈.java
- **문제 이름**: 지게차와 크레인
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/388353
board 테두리에 패딩을 주어 0,0부터 bfs로 체크하였습니다!
백준 치즈 문제랑 비슷하다는 힌트를 듣고.. 떠올려냈습니다..
> [3주차] 지게차와 크레인 - 이수빈

- MAR/WEEK3/비밀_코드_해독/박재환.java
- **문제 이름**: 비밀 코드 해독 
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/388352
처음 생각했던 방식은 각 시도마다 나올 수 있는 조합을 구한 뒤, 그 조합들의 조합을 통해 정답을 도출해내려했습니다. 
이렇게 코드를 짜니 조합을 조합하는 과정에서 코드가 너무 복잡해졌으며, 무엇보다 필요없는 중복 연산이 너무 많아졌습니다. 
인터넷에서 힌트를 얻어 반대로 생각해보았습니다. 
우선 주어진 정수 범위에서 만들 수 있는 5자리 비밀번호의 모든 조합을 구했습니다. 이때 비밀번호는 오름차순으로 정렬되어있다는 것을 생각해야합니다. 즉 백트래킹 없이 그냥 계속 증가만 시키면 됩니다. 
이후 비밀번호가 생성되었다면, 시도했던 비밀번호와 대조하여 일치하는 개수가 맞는지 판단 후, 모든 시도의 경우와 일치한다면 정답으로 세어주었습니다. 
이렇게 문제를 풀게되면 nC5 로 모든 조합을 구한 뒤, 최대 5^시도 횟수 의 시간 복잡도로 문제를 해결할 수 있었습니다. 
문제가 풀리지 않는다면 앞으로는 한 번 더 반대로 생각해보는 습관을 길러야겠어요
> [3주차] 비밀 코드 해독 - 박재환

- MAR/WEEK3/홀짝트리/박재환.java
- **문제 이름**: 홀짝트리
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/388354
핵심 개념은 각 노드의 진출 차수는 루트 노드가 아닐 때 1 감소한다 라는 개념입니다. 
Root 노드일 때 -> Root 노드가 아닐 때 경우를 확인해보면 
짝수 노드 -> 역짝수 노드
홀수 노드 -> 역홀수 노드
역짝수 노드 -> 짝수 노드
역홀수 노드 -> 홀수 노드
의 규칙성을 갖게 됩니다.
따라서 각 그래프의 집합을 구해준 뒤, 모든 노드의 진입차수를 기준으로 해당 집합이 홀짝 트리인지, 역홀짝 트리인지 구분하였습니다.
처음에 구현으로 접근하였다가, 시간 초과가 떠서 이것저것 수정하다보니 코드가 깨끗하지는 않네요...
최적화 부분이 아직 어려운거같습니다..
> [3주차] 홀짝트리 - 박재환

- MAR/WEEK3/완전범죄/정연수.java
- **문제 이름**: 완전범죄
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/389480
초기 부분집합을 고려했으나 너무 오래걸립니다.
해법을 모르겠어서 찾아 보았습니다.
가로축을 B의 크기 별로 두는 발상이 포인트인 것 같습니다.
각각의 B의 크기에 대해서 가장 작은 A의 크기
초기화를 MAX_VALUE 로 하니까 더하게 되니 음수가 됩니다.
조십해야겠습니다.
> [3주차] 완전범죄 - 정연수

- MAR/WEEK3/봉인된_주문/정연수.java
- **문제 이름**: 봉인된 주문
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/389481
자리수 와 진법에 따른 문자열 변환
예) 3자리수의 120 번째 수면 
120 / 100 = 1
1 + 1
2XX
20 / 10 = 2
0 + 2
220 입니다.
이때의 예시는 3자리 수면 백의 자리는 1 시작, 10의 자리는 0 시작이기 때문
> [3주차] 봉인된주문 - 정연수

- MAR/WEEK3/비밀_코드_해독/정연수.java
- **문제 이름**: 비밀코드 해독
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/388352
모든 조합으로 겹치는지 확인 합니다.
5개의 수만 뽑기 때문에 할만한것 같습니다.
> [3주차] 비밀코드해독 - 정연수

- MAR/WEEK3/홀짝트리/정연수.java
- **문제 이름**: 홀짝 트리
- **문제 링크**: ****
우선 union find 로 트리들을 나누어 줍니다. (트리이기 때문에 유파 그냥 써도 됩니다.)
각각의 트리를 보면서 노드들이 root 가 아닐 경우의 상태가 하나만 다르면 됩니다.
루트가 아닌 노드를 루트로 바꾸면
홀짝 -> 역홀짝
역홀짝 -> 홀짝
이렇게 바뀌게 됩니다.
따라서 하나만 다른 트리를 찾으면 해당 루트가 무엇인지 알기 때문에 그거에 +1
> [3주차] 홀짝트리 - 정연수

- MAR/WEEK3/지게차와_크레인/정연수.java
- **문제 이름**: 지게차와 크레인
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/388353?language=java
boj 치즈와 비슷한 문제입니다. 
뺄 물건을 우선 칠하고 한번에 빼고 밖이랑 맞닿아 있는지 봅니다.
> [3주차] 지게차와크레인 - 정연수

- MAR/WEEK4/경주로_건설/정한슬.java
- **문제 이름**: 경주로 건설
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/67259
1. 최단 경로를 계산한다.
2. queue에 int[]{row, col, 이전 방향, 직선 갯수, 코너링 갯수}을 넣는다.
1> 다음으로 갈수있을때 (벽이 아니고, board 밖이 아닐때) 직선 갯수 + 1를 해준다.
2> 이전 방향과 현재 direction 방향이 다를때는 코너링 갯수 + 1을 해준다.
.. pr 미리 하는게 좋네요....
> [4주차] 경주로 건설 - 정한슬

- MAR/WEEK4/퍼즐_조각_채우기/박재환.java
- **문제 이름**: 퍼즐 조각 채우기
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/84021
각 격자 ( game_board, table ) 들에서 추출할 수 있는 도형을 추출하였습니다. 
이후 table 에서 추출한 도형들을 회전 시켜, 이를 game_board 와 일치하는 경우가 있다면 개수를 카운트 해주었습니다.
이때 도형을 회전시키는 과정에서, 배열을 읽는 순서로 도형을 돌리는 규칙성을 찾아 비트마스킹 개념으로 해결하였습니다.
연수님이 도와주셔서 겨우겨우 반례 찾았습니다...........🥲
> [4주차] 퍼즐 조각 채우기 - 박재환

- MAR/WEEK4/자물쇠와_열쇠/박재환.java
- **문제 이름**: 자물쇠와 열쇠
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/60059
딱 문제를 보자마자 떠오르는 방법은 완전 탐색이여서, 완전 탐색으로 해결했습니다. 
열쇠가 가질 수 있는 경우는 총 4가지, 격자의 최대 크기는 20 x 20 이라 무리 없을거라 생각하였습니다. 
열쇠를 한 번씩 돌려가며, 모든 격자의 위치에 대입 후 본 자물쇠가 모두 채워지는지 확인하였습니다.
이게 되네
> [4주차] 자물쇠와 열쇠 - 박재환

- MAR/WEEK4/기지국_설치/박재환.java
- **문제 이름**: 기지국 설치
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/12979
생각보다 단순하게 풀었습니다!
기지국은 양쪽 ( 왼쪽, 오른쪽 ) 으로 전파를 전달할 수 있다라고 문제에서 제시하고 있어, 전파가 닿지 않는 영역을 구해, 해당 구역을 몇 개의 기지국을 이용해 커버할 수 있는지 계산하였습니다. 
처음엔 배열을 사용해 풀었었는데, 이때 생각한 시간 복잡도는  O(N) 이였습니다. 즉 최악의 경우 2초였는데, 정확성 태스트에서 모두 0.0x 초로 통과하여 괜찮겠구나 생각했는데, 효율성에서 통과하지 못했습니다. 
따라서 배열을 사용하여 순차적으로 탐색하지 않고, 입력과 동시에 포인터 개념을 활용하여, 영역을 계산 후 O(1) 의 시간 복잡도로 문제를 해결하였습니다.
자원을 아낍시다!
> [4주차] 기지국 설치 - 박재환

- MAR/WEEK4/로봇_조종하기/박재환.java
- **문제 이름**: 로봇 조종하기
- **문제 링크**: https://www.acmicpc.net/problem/2169
주어지는 격자의 크기가 너무 커서 DFS 로는 불가능할 것이라고 생각하였습니다. 
DP 를 사용해서 문제를 해결했습니다. 
문제를 크게 볼 때 (i, j) 의 위치로 올 수 있는 위치는 (i-1, j), (i, j-1), (i, j+1) 총 3가지 경우입니다. 
한 번에 DP 로 해결하자니 우측에서 좌측으로 오는 방향을 처리하는 것이 생각이 나지 않았습니다. 따라서 총 2번 누적 최대값을 구했습니다. 
1. 왼쪽에서 오른쪽으로 오는 경우 + 위에서 아래로 내려오는 경우
2. 오른쪽에서 왼쪽으로 오는 경우 + 위에서 아래로 내려오는 경우
이후 두 값을 비교하여 최대 값을 갱신해주었습니다. 
https://softeer.ai/practice/7369
위 문제와 비슷하다고 느껴서 거의 비슷하게 접근했습니다!
> [4주차] 로봇 조종하기 - 박재환

- MAR/WEEK4/퍼즐_조각_채우기/정연수.java
- **문제 이름**: 퍼즐 조각 채우기
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/84021
미친 구현입니다. 각각의 빈칸과 조각을 분리한 후 매치 시키면 됩니다. (돌리면서)
> [4주차] 퍼즐 조각 채우기 - 정연수

- MAR/WEEK4/자물쇠와_열쇠/정연수.java
- **문제 이름**: 자물쇠와 열쇠
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/60059
구현입니다. 
새로운 락을 만들어서 안에 열쇠를 채우고 검증하는 방식입니다.
> [4주차] 자물쇠와 열쇠 - 정연수

- MAR/WEEK4/로봇_조종하기/정연수.java
- **문제 이름**: 로봇 조종하기
- **문제 링크**: https://www.acmicpc.net/problem/2169
dp 였습니다.
왼쪽 and 아래만 있을때, 오른쪽 and 아래만 있을때로 생각해서 dp
> [4주차] 로봇 조종하기 - 정연수

- MAR/WEEK4/경주로_건설/정연수.java
- **문제 이름**: 경주로 건설
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/67259#
dfs 에 가지치기를 열심히 했습니다.
여기서 dfs 가지치기에서의 포인트는 중간의 값이 내가 다음 갈 곳 보다 크다면 굳이 갈 필요가 없습니다.
위 처럼만 하면 24 번이 틀리게 되는데, 그 이유는 코너에서 500 이 추가되므로 두 칸의 값의 차이가 500 미만이라면 방향이 좋은 길이 최적이 됩니다. 따라서 
`if (visit[nxtRow][nxtCol] <= nxtCount - 500) continue;` 이렇게 해주어야 합니다.
> [4주차] 경주로 건설 - 정연수

- MAR/WEEK4/기지국_설치/정연수.java
- **문제 이름**: 기지국 설치
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/12979
각각의 빈 곳을 구해서 몇개의 기지국이 필요한지 계산하여 더합니다.
> [4주차]기지국 설치 - 정연수

- MAR/WEEK4/기지국_설치/이수빈.java
- **문제 이름**: 기지국 설치
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/12979
설치된 기지국 기준으로 범위에 닿지 않는 이전의 아파트들 개수를 세서 구해줬습니다!
첨엔 이분탐색인가 했는데 그냥 구현이었네여
> [4주차] 기지국 설치 - 이수빈

- APR/WEEK1/1로_만들기/정연수.java
- **문제 이름**: 1로 만들기
- **문제 링크**: https://www.acmicpc.net/status?user_id=jack0810&problem_id=1463
간단한 dp입니다
> [4월 1주차] 1로만들기 - 정연수

- APR/WEEK1/집합의_표현/박재환.java
- **문제 이름**: 집합의 표
- **문제 링크**: https://www.acmicpc.net/problem/1717
각 집합을 기준으로 특정 원소가 해당 집합에 포함되어 있는지, 혹은 특정 원소를 해당 집합에 포함시키는 대표적인 Union-Find 문제입니다.
시험에 이런 문제만 나왔으면..
> [4월 1주차] 집합의 표현 - 박재환

- APR/WEEK1/1로_만들기/박재환.java
- **문제 이름**: 1로 만들기 
- **문제 링크**: https://www.acmicpc.net/problem/1463
어디서 많이 본 문제라 처음 보자마자 DP 로 풀어야겠다고 생각하였습니다. 
Bottom Up 방식으로 낮은 값부터, 목표 값까지 역으로 횟수롤 세어가며, 최소값으로 갱신해주었습니다.
DP 어려워요..
> [4월 1주차] 1로 만들기 - 박재환

- APR/WEEK1/1로_만들기/이수빈.java
- **문제 이름**: 1로 만들기
- **문제 링크**: https://www.acmicpc.net/problem/1463
15868KB, 104ms
dp로 풀었습니다!
실습 문제랑 같아서 좋네요 ㅎㅎ 근데 전 dp 너무 어려운 것 같아요... 이 문제도 사실 한슬언니 코드 참고해서 풀엇어요....
> [4월 1주차] 1로 만들기 - 이수빈

- APR/WEEK1/집합의_표현/이수빈.java
- **문제 이름**: 집합의 표현
- **문제 링크**: https://www.acmicpc.net/problem/1717
57332KB
1300ms
union find로 풀었습니다!
유니온파인드 까먹을락말락 했는데 복습해서 좋았습니다~
> [4월 1주차] 집합의 표현 - 이수빈

- APR/WEEK2/접두사_찾기/정한슬.java
- **문제 이름**: 접두사 찾기
- **문제 링크**: https://www.acmicpc.net/problem/14426
트라이로 풀이했습니다.
그냥 string startWith 썼었는데 시간초과 났었습니다 ㅎㅎ
> [4월 2주차] 접두사 찾기 - 정한슬

- 정한슬.java
- **문제 이름**: 친구 네트워크
- **문제 링크**:  https://www.acmicpc.net/problem/4195
숫자 노드가 아니라 사람 이름이라서, Map으로 인덱스를 지정하고 나머지는 u-f 로직과 똑같습니다!
그리고 그 집합에 총 몇명의 친구가 있는지 확인하기 위해서 단순히 rank를 ++하던것에서 부모노드가 되는 rank에 합쳐지는 rank의 수를 합해주어야합니다.
또 박재환이야~를 보고 자극받아서 풀어봣씸니더
> [4월] 친구 네트워크 - 정한슬

- APR/WEEK2/평범한_배낭/정한슬.java
- **문제 이름**: 평범한 배낭
- **문제 링크**:  https://www.acmicpc.net/problem/12865
knapsack 0/1 문제! 재환이 pr 덕에 수업때도 이해를 바로 했습니당
냅색 문제를 연속으로 풀어서 약간 습관적으로 칠 수 있게 된거같은데.. 나중엔 어찌될지 모르겠오요
> [4월 2주차] 평범한 배낭 - 정한슬

- APR/WEEK2/최단경로/정한슬.java
- **문제 이름**:  최단 경로
- **문제 링크**:  https://www.acmicpc.net/problem/1753
다익스트라... PQ,, 사용...
Umm,,,,,,
> [4월 2주차] 최단 경로 - 정한슬

- APR/WEEK2/최소_스패닝_트리/정한슬.java
- **문제 이름**: 최소 스패닝 트리
- **문제 링크**: https://www.acmicpc.net/problem/1197
먼저 하나를 트리에 연결해놓고 비트리 정점과 트리 정점을 구분해서 최소 비용을 구하는 최소신장트리(MST) 프림 복습했습니다 :)
분명 수업때 완벽히 이해했다고 생각했는데 또 바로바로 안떠오르네윰 : ( (
> [4월 2주차] 최소 스패닝 트리 - 정한슬

- APR/최소비용_구하기_2/박재환.java
- **문제 이름**: 최소 비용 구하기 2
- **문제 링크**: https://www.acmicpc.net/problem/11779
메모리 : 64048 KB
시간 : 524 ms
똑같은 다익스트라로 접근하되, 현재까지의 경로를 저장하는 List 를 가지고 있는 클래스를 정의하여 사용했습니다.
ㅎㅎ,,,, 재밌는 문제였어요
> [4월 2주차] 최소 비용 구하기 2 - 박재환

- APR/평범한_배낭/박재환.java
- **문제 이름**: 평범한 배낭
- **문제 링크**: https://www.acmicpc.net/problem/12865
메모리 : 14776 KB
시간 : 132 ms
DP 의 대표적인 Knapsack 알고리즘입니다. 
현재의 배낭 무게에 넣을 수 있는 최대 가치를 넣는 방식으로 값을 갱신해주었습니다. 
이전에 수빈님이 왜 역방향으로 진행하는지에 대한 의문을 가지셔서 저도 이번 기회에 알아보았습니다.
https://www.notion.so/Knapsack-1cc78fa9b0f980ef9eaff21b9498e719?pvs=4
역방향으로 진행할 경우 중복된 물건을 사용하지 않고, 정방향의 경우 중복해서 물건을 사용하는 경우가 생기게 됩니다. 
원래 이해보단 그냥 외우는 편이였는데, 이번기회에 알게되었습니다.
> [4월 2주차] 평범한 배낭 - 박재환

- APR/최단경로/박재환.java
- **문제 이름**: 최단경로
- **문제 링크**: https://www.acmicpc.net/problem/1753
메모리 : 124376 KB
시간 : 1584 ms
주어진 시작점에서 다른 모든 정점으로의 최단 경로 즉, 다익스트라 문제입니다. 
특별한 응용은 없어서 어렵지 않게 해결했습니다.
> [4월 2주차] 최단경로 - 박재환

- APR/접두사_찾기/박재환.java
- **문제 이름**: 
- **문제 링크**: 
Set 의 특성인 contains 의 실행 시간이 O(1) 인 특성을 이용하였습니다. 
사실 트라이 문제인것을 인지는 했지만, 넘모 어려운걸요
> [4월 2주차] 접두사 찾기 - 박재환

- APR/최소_스패닝_트리/박재환.java
- **문제 이름**: 최소 스패닝 트리
- **문제 링크**: https://www.acmicpc.net/problem/1197
메모리 : 55816 KB
시간 : 572 ms
간선의 개수가 10만개로, 적지 않은 양이라고 생각하였습니다. 
따라서 MST 를 구하는 알고리즘인 크루스칼과 프림 중, 간선의 개수가 많을 때 효과적인 PRIM 을 사용하였습니다.
업서용
> [4월 2주차] 최소 스패닝 트리 - 박재환

- APR/WEEK3/여행_가자/이수빈.java
- **문제 이름**: 여행 가자
- **문제 링크**: https://www.acmicpc.net/problem/1976
유니온 파인드로 풀었습니다!
> [4월 3주차] 여행 가자 - 이수빈

- APR/WEEK2/평범한_배낭/이수빈.java
- **문제 이름**: 평범한 배낭
- **문제 링크**: https://www.acmicpc.net/problem/12865
knapsack 문제로 풀었습니다!
> [4월 2주차] 평범한 배낭 - 이수빈

- APR/WEEK3/여행가자/정한슬.java
- **문제 이름**: 여행 가자
- **문제 링크**: https://www.acmicpc.net/problem/1976
U-F로 연결 해놓고 뿌리가 같으면(부모가 같으면) 연결된것이므로 여행 계획대로 여행할 수 있다고 풀었습니다.
.. 어떻게 U-F가 바로 생각나는 지,, ㅠ_ㅠ 저는 dfs, bfs로 풀고싶었는데 아직도 dfs bfs가 벅차네욤,, ㅎ..ㅎ
> [4월 3주차] 여행 가자 - 정한슬

- APR/WEEK3/우수_마을/정한슬.java
- **문제 이름**: 우수 마을
- **문제 링크**: https://www.acmicpc.net/problem/1949
dp 배열을 만들고 해당 마을을 우수마을로 선택했을 땐 1로, 선택하지 않았을 땐 0 에 저장합니다. 우수마을로 선택했을 때는 연결되어있는 다음 마을은 반드시 0(선택하지 않음)인 것을 합해야하고 우수마을로 선택하지 않았을 때는 연결되어있는 다음 마을을 선택했을때 (1), 선택하지 않았을때(0)값 중 큰값을 합합니다.. 
dp + dfs로 풀이 
젠또디피.. ㅜ_ㅜ
> [4월 3주차] 우수 마을 - 정한슬

- APR/WEEK3/플로이드/정한슬.java
- **문제 이름**: 플로이드
- **문제 링크**: https://www.acmicpc.net/problem/11404
플로이드-워샬로 풀이했습니다..!
흠,,
> [4월 3주차] 플로이드 - 정한슬

- APR/WEEK3/네트워크_연결/정한슬.java
- **문제 이름**: 네트워크 연결
- **문제 링크**: https://www.acmicpc.net/problem/1922
Prim으로 풀었습니다!
> [4월 3주차] 네트워크 연결 - 정한슬

- APR/WEEK3/플로이드/박재환.java
- **문제 이름**: 플로이드
- **문제 링크**: https://www.acmicpc.net/problem/11404
플로이드 워셜 알고리즘 그 자체 문제였습니다. 
다만 INF 를 문제에서 최대 거리가 100000 이라고 하여 100001 로 설정하였는데, 계속 97% 에서 실패하여, 혹시나 해서 바꿔보았더니 통과하였습니다. 
최대 범위를 잘 잡아야합니다..
> [4월 3주차] 플로이드 - 박재환

- APR/WEEK3/가장_긴_바이토닉_부분_수열/박재환.java
- **문제 이름**: 가장 긴 바이토닉 부분 수열
- **문제 링크**: https://www.acmicpc.net/problem/11054
LIS 를 활용하여 양방향 DP 를 사용해 해결할 수 있는 문제였습니다. 
연수님이 설명해주신 LIS 를 이분탐색으로 구현해보았습니다. 다만 한 가지 주의해야할 부분은 list 는 말 그대로, 현재 최대 LIS 의 길이이므로, 실제 현재 타겟 수가 마지막에 위치하는 LIS 의 수열의 길이가 아니므로, 이때는 현재 타겟 수가 들어갈 인덱스 값에 + 1 더해주었습니다. 
그리고, 교차되는 값을 비교할 때, 해당 위치의 값이 중복으로 들어가므로 1 제거해주었습니다.
이분 탐색을 이용해서 푸는법을 알게되어 뿌듯합니다 ( 연수형 고마워요ㅎㅅㅎ )
> [4월 3주차] 가장 긴 바이토닉 부분 수열 - 박재환

- APR/WEEK3/우수_마을/박재환.java
- **문제 이름**: 우수 마을
- **문제 링크**: https://www.acmicpc.net/problem/1949
트리 DP 라는 것을 사용해 풀었습니다. 
DP[a][0] 은 a 정점에서 a 를 포함하지 않을 때의 최대값
DP[a][1] 은 a 정점에서 a 를 포함할 때의 최대값
을 나타냅니다. 탑다운? 바텀업? 정확하게 뭐라해야할지 잘 모르겠습니다... 조합처럼 **포함하는가/포함하지 않는가** 로 구분하였습니다.
어려웠어요...
> [4월 3주차] 우수 마을 - 박재환

- APR/WEEK3/네트워크_연결/정연수.java
- **문제 이름**: 네트워크 연결
- **문제 링크**: 
> [4월 3주차] 네트워크 연결 - 정연수

- APR/WEEK4/가사_검색/정한슬.java
- **문제 이름**: 가사 검색
- **문제 링크**: 
???로 시작하면 endWith 메서드를 사용해서 reverseTrie에서 찾았고 그렇지 않으면(??가 뒤에 있는 경우) startWith메서드를 사용해서 Trie에서 찾았습니다. 중복과 많은 단어가 있는 경우 시간초과가 나서 단어 길이 Length에 해당 트라이들을 key, value로 map을 이용해서 넣었고 찾으려는 단어 길이 마다 해당 맵에서 trie가 있으면 찾고, 없으면 0을 넣었습니다.
> [4월 4주차] 가사 검색 - 정한슬

- APR/WEEK4/점프/정한슬.java
- **문제 이름**: 점프
- **문제 링크**: https://www.acmicpc.net/problem/1890
아래, 오른쪽으로만 가므로 dp로 row, col 별로 갱신해서 최종 적으로 맨 마지막 칸에서의 값을 return 했습니다.
> [4월 4주차] 점프 - 정한슬

- APR/WEEK4/특정한_최단_경로/정한슬.java
- **문제 이름**: 특정한 최단 경로
- **문제 링크**:  https://www.acmicpc.net/problem/1504
다음과 같이 풀이했습니다.
* 총 3가지의 다익스트라 distance 배열을 만든다.
* 1. 시작 정점에서부터 모든 정점까지의 최단 거리 저장
* 2. 반드시 자나가야하는 정점1에서 모든 정점까지의 최단거리 저장
* 3. 반드시 지나가야하는 정점2에서 모든 정점까지의 최단 거리 저장
* 
* 그럼 문제에서 원하는 경로는 2가지로 생각할 수 있다.
* 1. 0 -> mustPassVertex1 -> mustPassVertex2 -> N - 1
* 2. 0 -> mustPassVertex2 -> mustPassVertex1 -> N - 1
* 그 중 최단 거리를 갱신
> [4월 4주차] 특정한 최단 경로 - 정한슬

- APR/WEEK4/삼각형으로_자르기/정한슬.java
- **문제 이름**: 삼각형으로 자르기
- **문제 링크**:  https://www.acmicpc.net/problem/1198
삼각형 넓이 구하는 공식만 잘 넣으면...  됩니다..
휴먼 에러,,
> [4월 4주차] 삼각형으로 자르기 - 정한슬

- MAY/WEEK1/미로_만들기/박재환.java
- **문제 이름**: 미로 만들기
- **문제 링크**: https://www.acmicpc.net/problem/2665
같은 조건으로 방문을 하지 않는다 라는 풀이 방법을 생각하여, 3차원 visited 배열을 사용하여 풀이하였습니다.
0-1 BFS 를 사용하여 풀어보았는데, 훨씬 빠르고 풀이도 간단하였습니다.
> [5월 1주차] 미로 만들기 - 박재환

- MAY/WEEK1/활자_그래프/박재환.java
- **문제 이름**: 활자 그래프
- **문제 링크**: https://softeer.ai/practice/7704
각 그래프별로 최단 경로를 구해두었습니다. 
이때 입구와 출구가 정해져있어 다익스트라 알고리즘을 사용하였고, 
이전에 구해둔 경로를 이용해 문제를 해결하였습니다.
계속해서 최대값의 범위 때문에 틀렸는데, 1_000_000_000_000_000_000 까지는 경로가 존재할 수 있어 
1_000_000_000_000_000_001 로 설정하였더니 통과하였습니다.
> [5월 1주차] 활자 그래프 - 박재환

- APR/WEEK4/동전1/박재환.java
- **문제 이름**: 동전 1
- **문제 링크**: https://www.acmicpc.net/problem/2293
DP 로 풀었습니다.
배낭 채우기와 다르게 최대 가치를 구하는 것이 아닌, 모든 경우의 수를 구하는 문제입니다.
바텀업 방식으로 앞에서부터 값을 채워나갔습니다. 또한 동전은 중복될 수 있으므로 이전의 값을 누적해서 사용하였습니다. 
DP 는 너무 헷갈려요
> [4월 4주차] 동전 1 - 박재환

- APR/WEEK4/가사_검색/박재환.java
- **문제 이름**: 가사 검색
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/60060
가사 ( words ) 를 Map 을 사용해 길이별로 저장 하였습니다. 
이후 찾고자하는 키워드 ( queries ) 를 ? 부분을 a , z 로 바꿔 해당 키워드를 탐색의 기준으로 하여 Map 에 저장되어 있는 가사 ( words ) 들이 포함된 개수를 이분 탐색을 통해 찾아주었습니다.
이걸 어떻게 이분탐색을 생각해내는건지 모르겠어요
> [4월 4주차] 가사 검색 - 박재환

- APR/WEEK4/특정한_최단_경로/박재환.java
- **문제 이름**: 특정한 최단 경
- **문제 링크**: https://www.acmicpc.net/problem/1504
1 -> N 으로 가는 경로에서 임의의 두 정점을 반드시 경유해야하는 문제로, 플로이드 워셜과 다익스트라 중 선택애햐 하는 문제입니다. 
정점의 개수가 최대 800 개 이므로 플로이드 워셜을 사용하면 800^3 으로 시간초과가 발생하므로, 다익스트라를 사용하였습니다.
나올 수 있는 경로는 
1 -> A -> B -> N
1 -> B -> A -> N 
두 가지로, 각 경우에서의 최단 경로를 찾아 비교하였습니다.
> [4월 4주차] 특정한 최단 경로 - 박재환

- APR/WEEK4/삼각형으로_자르기/박재환.java
- **문제 이름**: 삼각형으로 자르기
- **문제 링크**: https://www.acmicpc.net/problem/1198
주어지는 점의 수가 35 개, 즉 35 개의 점 중 3개의 점을 선택하는 35C3 조합 문제라고 생각하였습니다. 
세 점으로 삼각형의 넓이를 구하는 공식은 아래의 블로그를 참조하였습니다. 
https://m.blog.naver.com/eandimath/221760895905
> [4월 4주차] 삼각형으로 자르기 - 박재환

- MAY/WEEK1/미로_만들기/정한슬.java
- **문제 이름**: 미로 만들기
- **문제 링크**: https://www.acmicpc.net/problem/2665
일반 BFS는 최단거리로만 생각해서 풀이가 안되서.. 0-1 BFS 재환이가 언급한 방법으로 풀었습니다,, 몰라서 참고해서 풀었어요..! 
이런 풀이도 있구나 싶었습니다.. 좋은 문제 추천 감사용
> [5월 1주차] 미로 만들기 - 정한슬

- MAY/WEEK1/토마토/정한슬.java
- **문제 이름**: 토마토
- **문제 링크**: https://www.acmicpc.net/problem/7569
2차원 토마토 부터 풀고.. 3차원만 더해줬습니다.. 
끗
> [5월 1주차] 토마토 - 정한슬

- MAY/WEEK1/활자_그래프/정한슬.java
- **문제 이름**: 활자 그래프
- **문제 링크**: 
.. 진짜 좀 치사한 문제,,
> [5월 1주차] 활자 그래프 - 정한슬

- APR/WEEK4/점프/이수빈.java
- **문제 이름**: 점프
- **문제 링크**: https://www.acmicpc.net/problem/1890
11792KB, 68ms
도착지부터 거꾸로 DP 했습니다!
long 주의!
> [4월 4주차] 점프 - 이수빈

- APR/WEEK4/동전1/이수빈.java
- **문제 이름**: 동전1
- **문제 링크**: https://www.acmicpc.net/problem/2293
각 동전 별로 만들 수 있는 모든 값에 대해 구해줬습니다. (DP)
> [4월 4주차] 동전1 - 이수빈

- APR/WEEK4/특정한_최단_경로/이수빈.java
- **문제 이름**: 특정한 최단 경로
- **문제 링크**: https://www.acmicpc.net/problem/1504
시작정점, 중간 경유 정점들에 대해 다익스트라를 한 후,
1. 시작 -> 중간1 -> 중간2 -> 도착
2. 시작 -> 중간2 -> 중간1 -> 도착
이 2개 중 최솟값을 답으로 출력했습니다.
풀면서 설마 이게 맞을까? 했는데 정답인 이슈..
> [4월 4주차] 특정한 최단 경로 - 이수빈

- MAY/WEEK1/미로_만들기/이수빈.java
- **문제 이름**: 미로 만들기
- **문제 링크**: https://www.acmicpc.net/problem/2665
덱을 이용한 bfs로 방문횟수에 따라 덱의 앞, 뒤에 값을 넣어주었습니다
> [5월 1주차] 미로 만들기 - 이수빈

- MAY/WEEK1/토마토/이수빈.java
- **문제 이름**: 토마토
- **문제 링크**: https://www.acmicpc.net/problem/7569
3차원 배열에 대해 bfs로 풀었습니다!
> [5월 1주차] 토마토 - 이수빈

- APR/WEEK4/삼각형으로_자르기/이수빈.java
- **문제 이름**: 삼각형으로 자르기
- **문제 링크**: https://www.acmicpc.net/problem/1198
조합 문제입니당
> [4월 4주차] 삼각형으로 자르기 - 이수빈

- MAY/WEEK1/미로만들기/정연수.java
- **문제 이름**: 미로만들기
- **문제 링크**: https://www.acmicpc.net/problem/2665
얼만큼을 깨고 지나왔는지 카운트 합니다.
> [5월 1주차] 미로만들기 - 정연수

- APR/WEEK4/가사검색/정연수.java
- **문제 이름**: 가사검색
- **문제 링크**: 
trie
> [4월 4주차] 가사검색 - 정연수

- APR/WEEK4/점프/정연수.java
- **문제 이름**: 점프
- **문제 링크**: 
간단한 dp 입니다
> [4월 4주차] 점프 - 정연수

- APR/WEEK4/특정한_최단_경로/정연수.java
- **문제 이름**: 특정한 최단 경로
- **문제 링크**: 
각각 어디를 지나야 하는지를 구한 후 각각 맞추어 구합니다.
> [4월 4주차] 특정한 최단 경로 - 정연수

- APR/WEEK4/동전1/정연수.java
- **문제 이름**: 동전 1
- **문제 링크**: 
dp
이 dp는 중복은 세지 않아야 하는 dp 입니다.
중복을 세면 안되므로 동전을 하나씩 놓는 방법
원래는 중복 허용이면 현재로 부터 몇칸 뒤를 봐야하는데 이아이는 안돼서 하나씩 놓아보는 방법을 사용한다.
> [4월 4주차] 동전 1 - 정연수

- APR/WEEK3/여행_가자/정연수.java
- **문제 이름**: 
- **문제 링크**: 
유파
> [4월 3주차] 여행가자 - 정연수

- APR/WEEK3/플로이드/정연수.java
- **문제 이름**: 
- **문제 링크**: 
다익스트라
> [4월 3주차] 플로이드 - 정연수

- MAY/WEEK2/우주신과의_교감/정한슬.java
- **문제 이름**: 우주신과의 교감
- **문제 링크**: https://www.acmicpc.net/problem/1774
크루스칼로 풀이했습니다..!! 근데 왜맞틀 + 4퍼틀이었는데.. 알고보니 거리 구할때 int dx  = x1 - x2 , int dy = y1 - y2로 해서 틀렸었습니다,,
> [5월 2주차] 우주신과의 교감 - 정한슬

- MAY/WEEK2/파티/정한슬.java
- **문제 이름**: 파티
- **문제 링크**: https://www.acmicpc.net/problem/1238
다익스트라 2번해서 마을 -> X 최단거리 + X -> 마을 최단거리를 구했습니다.
다익스트라는 출발지에서 모든 정점까지의 비용인 개념을 잊고 풀었더니 로직 생각하는거 자체를 헤맸어요,, 호호,,
단방향에만 사로잡혀서 역방향 그래프는 생각도 못했습니다 흑흑
> [5월 2주차] 파티 - 정한슬

- MAY/WEEK2/불/정한슬.java
- **문제 이름**: 불!
- **문제 링크**: 
BFS + BFS,,, 시간안에 탈출 할 수 있냐 없냐 로,, 풀었습니다. 
가장자리에서만 탈출 가능하다는 조건 + visited 갱신 순서에 따라 메모리 초과가 난다는 것... 그것때문에 너무 삽질을 했습니다.. 
으!!!
> [5월 2주차] 불! -정한슬

- MAY/WEEK3/동전_분배/박재환.java
- **문제 이름**: 동전 분배
- **문제 링크**: https://www.acmicpc.net/problem/1943
> [5월 3주차] 동전 분배

- MAY/WEEK2/하늘에서_별똥별이_빗발친다/박재환.java
- **문제 이름**: 하늘에서 별똥별이 빗발친다
- **문제 링크**: https://www.acmicpc.net/problem/14658
N, M 의 좌표가 너무 크기에 완전 탐색을 이용해서는 풀 수 없다고 생각하였습니다.
별의 개수는 최대 100 개 이므로, 이걸 이용해야한다 생각했습니다. 
처음에는 2 개의 좌표 조합으로 정사각형을 만들 수 있는지 판단하려했는데, 이렇게 되면 모든 경우를 판단하기 어렵고, 무엇보다 완벽하게 조건을 만족하는 경우가 거의 없을 것이라 생각했고 역시나 생각이 맞았습니다.
정사각형을 만들기 위해서 모든 별을 2중 for 문을 통해 별의 조합을 구하였고, 각 좌표에서 x, y 를 뽑아 좌상단 꼭짓점을 만들었습니다.
이부분이 꽤 어려웠는데, 정확하지는 않지만 정사각형의 변의 길이에 따라 두 별을 모두 포함할 수 있는 위치를 찾는다고 생각이 들었습니다.
https://softeer.ai/practice/6277
이 문제와 유사해서 이렇게 처음에 접근해보았으며 살짝 다른거같아요
> [5월 2주차] 하늘에서 별똥별이 빗발친다 - 박재환

- MAY/WEEK2/우주신과의_교감/박재환.java
- **문제 이름**: 우주신과의 교감
- **문제 링크**: https://www.acmicpc.net/problem/1774
문제에 내포되어 있는 방법을 사용하였습니다.
이미 연결되어 있는 우주신을 이용해 교감이 가능하다. -> Union-Find
통로들이 짧은 것을 선호한다. -> MST
Point to Point 로 모든 거리를 구해 MST 를 사용하였습니다.
오랜만에 MST, Union-Find 를 사용해서 조금 헷갈렸어요
> [5월 2주차] 우주신과의 교감 - 박재환

- MAY/WEEK2/고층_건물/박재환.java
- **문제 이름**: 고층 건물
- **문제 링크**: https://www.acmicpc.net/problem/1027
단순하게 문제를 보고 LIS 를 사용해 풀 수 있을거라고 생각해서 약 1시간반동안 삽질한 결과....
구할 수 없다는 것을 깨닫고# 📝 문제 정보
- **문제 이름**: 고층 건물
- **문제 링크**: https://www.acmicpc.net/problem/1027
단순하게 문제를 보고 LIS 를 사용해 풀 수 있을거라고 생각해서 약 1시간반동안 삽질한 결과....
구할 수 없다는 것을 깨닫고 기울기를 이용해서 문제를 풀었습니다. 
기울기가 양수의 값을 갖는다면 좌상향, 음수의 값을 갖는다면 우상향의 기울기를 갖게됩니다.
건물을 볼 수 있는 조건은, 이전 건물과의 기울기보다 |큰 기울기| 를 갖는다면 건물을 볼 수 있습니다. 
Double.MAX_VALUE / Double.MIN_VALUE 를 사용하면, 1.XXX~ -4.XXX~ 의 값을 갖는데, 이는 정수/실수로 표현 가능한 가장 큰 유한값으로 정확하지 않은 결과를 얻을 수 있습니다.
Double.POSITIVE_INFINITY / Double.NEGATIVE_INFINITY 를 사용하여 Infinity / -Infinity 로 설정해야 …
> [5월 2주차] 고층 건물 - 박재환
