FEB_WEEK3/로드_밸런서_트래픽_예측/박재환.java
- **문제 이름**: 로드 밸런서 트래픽 예측
- **문제 링크**: https://softeer.ai/practice/6263
위상 정렬을 이용한 풀이 방법을 사용하였습니다. 
각 노드로 들어오는 간선의 개수를 이용하여, 간선의 개수가 적은 순으로 정렬해주었습니다. 이후 정렬된 상태는 상위 노드에서 하위 노드로의 형태를 보여줍니다. 
정렬된 노드들을 이용하여 하위 노드로의 업무 분배를 해주었습니다. 하위 노드들은 
**부모 노드의 업무 개수 / 하위 노드의 수**  만큼의 업무를 균등하게 배분받은 후 
**부모 노드의 업무 개수 % 하위 노드의 수** 만큼의 업무는 RR 방식을 이용하여 차례로 업무를 할당 받습니다. 
위상 정렬 알고리즘을 알지 못해서 접근 방법을 생각하지 못했습니다. 
https://youtu.be/7NZzLn374TA?si=cx6uZ3o16DYwAz8N
해당 강의를 참조하였고, 강의 내용을 숙지 후 스스로 코드를 작성하여 풀어보았습니다.
=> [3주차] 로드 밸런서 트래픽 예측 - 박재환

FEB_WEEK3/거리합_구하기/박재환.java
- **문제 이름**:  [21년 재직자 대회 본선] 거리 합 구하기
- **문제 링크**: https://softeer.ai/practice/6258
이번 문제는 트리의 특성을 이용할 수 있는 문제였습니다. 
문제의 풀이 방식은 루트노드를 기준으로 모든 거리의 합과, 각 노드들의 서브트리의 크기를 이용하여 상수시간 내에 모든 거리를 구할 수 있는 문제였습니다. 
총 2번의 DFS 가 필요합니다. 
첫 번째 DFS 는 바텀업 방식을 이용하여 각 노드의 서브트리의 크기와, 루트노드를 기준으로 하는 거리의 합을 구합니다.
두 번째 DFS 는 탑다운 방식을 이용하여 부모노드의 거리합으로부터 자식 노드의 거리합을 구합니다. 
자식 노드의 거리합 
= 부모 노드의 거리합 + (전체 노드 개수 - 서브 트리 노드 개수) * 부모노드와 자식 노드와의 거리 - (서브 트리 노드 개수) * 부모노드와 자식 노드와의 거리  
=> 부모 노드의 거리합 + 전체 노드 개수 - 2*서브 트리 노드 개수) * 부모노드와 자식 노드와의 거리 를 이용해 구할 수 있습니다.
처음엔 플로이드워셜 알고리즘이 생각났고, 이는 O(N^3) 의 시간복잡도로 해결할 수 없는 방법이였습니다. 또한 탐색을 줄이기 위하여 트리구조이기 때문에 부모노드와의 연결만 고려하는 방법도 생각해보았는데 이 또한 시간초과였습니다. 
트리의 특성을 이용하고, 재귀호출을 통하여 문제를 해결할 수 있었습니다.
아래는 참고한 …
=> [3주차] 거리합 구하기 - 박재환

FEB_WEEK4/사물인식_최소_면적_산출_프로그램/정한슬.java
- **문제 이름**: 사물인식 최소 면적 산출 프로그램 
- **문제 링크**: https://softeer.ai/practice/6277
점을 최소한 1개씩 포함하는 최소의 면적을 구하기 위해
색깔 별로 1개씩 다른 색깔과 판단하는 dfs 알고리즘을 선택했어야했습니다.
최악의 경우 소용없는 가지치기이지만, 현재까지 확인한 색깔들의 점을 갱신하여 넣은 넓이가 최소 넓이보다 같거나 크면 dfs에 들어가지 않도록 처리했습니다.
플랫한 시야 너무 어렵네요..,,
=> [4주차] 사물인식 최소 면적 산출 프로그램 - 정한슬

FEB_WEEK4/사물인식_최소_면적_산출_프로그램/박재환.java
- **문제 이름**: 사물인식 최소 면적 산출 프로그램
- **문제 링크**: https://softeer.ai/practice/6277
직사각형의 넓이를 구하기 위해서는 최대값 (x,y) 와 최소값 (x,y) 를 구하여 두 값의 차를 통해 넓이를 구하였습니다.
따라서 각 색상의 점 위치를 각각 기록해 놓는 배열을 생성하여 각 색상의 모든 점들의 조합을 통해 문제를 해결하였습니다.
또한 이렇게 접근할 경우 5^20 의 시간복잡도를 가지게 되는데, 이를 고려하여 이전에 구한 최소 면적보다 크기가 커지는 경우 가지치기를 통해 탐색 수를 감소시켰습니다.
가지 치기를 생각하지 못한 것은 아닌데, 조건문의 위치에 따라 탐색 시간이 달라질 수 있음을 몸소 느꼈습니다. 
최소 면적보다 현재 현적이 큰 경우 를 함수 호출 이후 실행하는 경우 스택에 쌓고 이를 빼내는 과정에서 시간초과가 나게 되었고, 애초에 해당 조건을 기준으로 하여 스택에 쌓고 이를 호출하는 과정을 제거하여 시간초과 늪에서 나올 수 있었습니다...
=> [4주차] 사물인식 최소 면적 산출 프로그램 - 박재환

FEB_WEEK4/사물인식_최소_면적_산출_프로그램/이수빈.java
- **문제 이름**: 사물인식 최소 면적 산출 프로그램 
- **문제 링크**: https://softeer.ai/practice/6277
실행시간 : 0.166초
메모리 : 12.33MB
dfs는 시간초과가 날 것이라고 생각해서 다른방법을 계속 생각해보다가 안풀려서 찾아봤는데 dfs로 되더군요..
파라미터로 color를 넘겨 다음 color를 선택하도록 dfs 하였습니다. 대신 현재의 최소면적보다 큰 면적을 가지는 경우엔 dfs를 들어가지 않도록 하였습니다.
가지치기를 한다해도 최악의 경우엔 시간초과가 날 거라고 생각했는데, 통과해서 왜인지 궁금합니다.. 모르겠어요..!
=> [4주차] 사물인식 최소 면적 산출 프로그램 - 이수빈

MAR/WEEK2/캐시/정연수.java
- **문제 이름**: 캐시
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/17680
해시 맵에 아이템을 두어 검색시 한번에 가져갈 수 있도록 구현하고 lruList 를 만들어서 가장 앞쪽에 옛날에 쓴 아이템을 유지하기 위해 linkedlist 로 구현하였습니다.
hashmap 에서 remove 를 할때 hashCode 를 기준으로 하니 remove(Object o) 와 remove(int O) 와 충돌이 나 오류가 발생하였습니다. int key 를 기준으로 remove 는 되도록 조심해야 할 것 같습니다.
찾아 보니
// remove(int index)가 아닌 remove(Object o)를 호출하도록 명시적 캐스팅
lruList.remove((Integer)key);
이런 식으로 명시적 캐스팅을 하면 remove(Object o) 로 되어 메서드 오버로딩에 의한 충돌이 나지 않는다고 합니다.
=> [2주차] 정연수 - 캐시

MAR/WEEK2/서버_증설_횟수/이수빈.java
- **문제 이름**: 서버 증설 횟수
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/389479
1. 시간별로 가동되는 서버의 개수를 관리하는 배열(serverCnt)을 생성한다.
2. 시간마다 반복문 돌며 해당 시간에 필요한 서버 개수를 구해준다.
3. 2번에서 구한 서버 개수가 serverCnt[time]보다 작다면, 증설할 서버 개수(serverCnt[time] - 2번의 개수)를 구해주고 serverCnt배열에 서버 최대 시간만큼 더해준다.
4. 증설할 서버 개수를 answer에 더해준다.
=> [2주차] 서버 증설 횟수 - 이수빈

MAR/WEEK2/서버_증설_횟수/정한슬.java
- **문제 이름**: 서버 증설 횟수
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/389479
1. 0시부터 23시까지 증설된 서버의 수를 저장할 int[] 배열을 만든다.
2. players 배열을 돌면서, 게임 이용자 수가 m 이상 일때  players[i] /m 몫 만큼의 서버가 증설된다.
-> 증설된 서버의 수를 저장
3. 증설된 서버는 연속된 뒤의 k - 1 index까지 유지가 된다.
=> [2주차] 서버 증설 횟수 - 정한슬

MAR/WEEK2/석유_시추/정한슬.java
- **문제 이름**: 석유 시추
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/250136
bfs로 풀었습니다.
1. 1인 곳마다 bfs로 탐색하여 연결되어 있는 영역의 크기를 구한다.
2. 영역의 크기를 구할때마다 새로운 col이면 set에 기록을 해둔다.
3. Map을 만들어 col별로 영역의 크기를 저장한다.
4. 1과 2에서 찾은 영역을 col별로 더해서 저장한다.
ex> col 1, 2, 3에 걸친 영역 8을 map.get(1) + 8, map.get(2) + 8, .. 으로 갱신한다.
처음에 curArea를 int[] 배열에 넣은 뒤에 다음 칸으로 옮길때 curArea + 1로 queue 넣는 거로 구현했는데 틀렸어용
=> [2주차] 석유 시추 - 정한슬

MAR/WEEK1/안전_영역/정한슬.java
- **문제 이름**: 안전 영역
- **문제 링크**: https://www.acmicpc.net/problem/2468
저는 이거 풀면서 석유 시추(2주차에 있음)이 생각 났었어요! 붙어있으면 같은 영역이라고 표현하기 위해 map을 썼고 queue에 넣어서 4방향 돌면서 가까이 인접한 칸인지 확인했습니다.
변수명 변경 안했습니다 :D
++ 실수로 지워서 다시 올립니다 ,,
=>  [1주차] 안전 영역 - 정한슬 

MAR/WEEK2/석유_시추/박재환.java
- **문제 이름**: 석유 시추
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/250136
초기 전처리 과정에 각 구역의 석유량을 구해놓았습니다.
누적 합을 구할 배열의 크기를 land.length 의 길이만큼 선언해둔 뒤, 각 칸마다 구할 수 있는 최대 누적 합을 구한 뒤, 최대 값을 구했습니다.
처음엔 Flood Fill 알고리즘을 사용하였을 때, 시간 초과가 발생하였고, 이를 줄이고자 List 에 각 석유의 구역과 영역의 크기를 저장해둔 뒤, 각 구역마다 List 를 순회하며 비교하였을 때는 한 개의 테스트 케이스에서 시간초과가 발생하였습니다ㅜ_ㅜ
=> [2주차] 석유 시추 - 박재환

MAR/WEEK2/서버_증설_횟수/박재환.java
- **문제 이름**: 서버 증설 횟수
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/389479
문제에서 주어진대로 시뮬레이션을 하나하나 돌려보았습니다. 
각 시간별 필요한 서버의 개수는 사용자/가용범위 의 정수 값이므로, 우선순위 큐를 사용하여 증설된 서버를 관리하였습니다.
각 시간을 기준으로하여 서버의 종료 시점을 계산해 우선순위 큐에 넣어주었고, 자연스럽게 빠른 시간 순으로 정렬되어 HEAD 값만 비교하여 회수되는 서버를 구했습니다.
문제를 풀고나서 수빈님 코드를 봤는데, 무식하게 구현으로 푸는 버릇을 좀 죽여놔야겠네요..ㅎㅎㅎ
=> [2주차] 서버 증설 횟수 - 박재환

MAR/WEEK3/봉인된_주문/박재환.java
- **문제 이름**: 봉인된 주문 
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/389481
처음 접근했던 방법으로 삽질을 좀 했습니다.... 
처음에 풀고자했던 방법은 순열을 이용해서 푸는 방법이였습니다.
1. 구하고자하는 인덱스가 속한 문자열 집합을 찾는다.
해당 단계에서는 구하고자 하는 인덱스인 n 이 속한 문자열의 집합, 즉 문자의 길이를 구하였습니다.
이로 인해 1 ~ n 까지가 아닌, 특정 길이의 문자열 내에서 순열을 이용해 n 번째 문자를 구하고자 하였습니다. 
2. bans 에 속한 원소들을 처리한다. 
1 단계에서 구하고자하는 문자열의 집합과, 해당 집합에서 찾고자하는 문자의 인덱스를 구했으므로, bans 를 탐색하며, 찾고자하는 문자열의 길이보다 적을 경우, 1단계에서 구한 집합 내의 인덱스를 증가 시켜주었고, 찾고자하는 문자열의 길이와 같은 경우, 이를 우선순위 큐에 사전순으로 저장해주었습니다. 
3. 순열을 생성하며 값을 도출한다.
이전의 단계에서 찾고자하는 원소의 집합과, 해당 집합 내에서 인덱스를 구했습니다.특정 문자열 길이의 순열을 생성하며 우선순위 큐의 HEAD 값과 비교하며 찾고자하는 원소에 도달할때까지 탐색하였습니다. 
정확도에서는 문제가 없지만, 시간 복잡도에서 문제가 생겼습니다. 
이를 해결하고자 탐색 범위를 더 줄이는 방법을 생각하였고, …
=> [3주차] 봉인된 주문 - 박재환

MAR/WEEK3/지게차와_크레인/박재환.java
- **문제 이름**: 지게차와 크레인 
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/388353
가로, 세로 각각 2만큼 늘린 크기의 2차원 배열을 생성하여, 창고를 배열로 저장하였습니다. 
지게차를 이용해 물건을 빼내는 로직이 전부였던 문제였습니다. 외부와 내부를 구분하여 물건을 빼주었습니다.
이때 예제 1번의 3번째 명령어에서 연달아 있는 물건을 뺄 수 없다는 조건이 있어 이부분만 주의해서 문제를 풀었습니다.
외부와 내부를 구분하는 로직은 BFS 를 활용하였습니다. (0,0) 위치에서 출발하여 상하좌우를 탐색하고, 빈 공간이면 이동하는 방식으로 구현하였습니다.
과제로 풀었던 백준의 치즈 문제와 동일한 문제입니다. 
https://www.acmicpc.net/problem/2636
=> [3주차] 지게차와 크레인 - 박재환

APR/WEEK1/가장_긴_증가하는_부분수열/정연수.java
- **문제 이름**: 가장 긴 증가하는 부분 수
- **문제 링크**: https://www.acmicpc.net/problem/11053
마찬가지로 간단한 1차원 dp입니다.
=> [4월 1주차] 가장 긴 증가하는 부분수열 - 정연수

APR/WEEK1/가장_긴_증가하는_부분_수열/박재환.java
- **문제 이름**: 가장 긴 증가하는 부분 수열 
- **문제 링크**: https://www.acmicpc.net/problem/11053
DP 를 사용해서 해결하였습니다. 
현재 값 이전의 원소들의 증가 부분 수열의 합을 이용하여 갱신하였습니다. 
이분 탐색을 사용해 풀고싶었는데, 이해하지 못했어요
연수님 믿습니다 ㅎㅋㅎ
=> [4월 1주차] 가장 긴 증가하는 부분 수열 - 박재환

APR/WEEK1/가장_긴_증가하는_부분_수열/이수빈.java
- **문제 이름**: 가장 긴 증가하는 부분 수열
- **문제 링크**: https://www.acmicpc.net/problem/11053
현재 원소보다 이전에 있는 원소들을 탐색하는 방식으로 했습니다 (dp)
문제 이름이 너무 기네여
=> [4월 1주차] 가장 긴 증가하는 부분 수열 - 이수빈

APR/WEEK3/가장_긴_바이토닉_부분_수열/정한슬.java
- **문제 이름**: 가장 긴 바이토닉 부분 수열
- **문제 링크**:  https://www.acmicpc.net/problem/11054
특정 인덱스에서 왼쪽배열(특정 인덱스를 끝으로 증가하는 수 저장), 오른쪽 배열(특정 인덱스를 시작으로 감소하는 배열)을 만들고 특정 인덱스에서 더하면 그것이 바이토닉 부분 수열의 길이가 됩니다.
자기자신은 포함이 안되므로 +1을 하여 답을 구했습니다.
=> [4월 3주차] 가장 긴 바이토닉 부분 수열 - 정한슬

APR/여행_가자/박재환.java
- **문제 이름**: 여행 가자
- **문제 링크**: https://www.acmicpc.net/problem/1976
메모리 : 17476 KB
시간 : 148 ms
문제에서 주어진 각 도시들이 서로 연결되어 있는지를 확인하면 된다고 생각하여 Union-Find 를 사용하였습니다. 
처음엔 이게 뭐지 싶었다가, 차분히 문제를 읽어보았습니다!
=> [4월 3주차] 여행 가자 - 박재환

APR/WEEK3/가장_긴_바이토닉_부분_수열/이수빈.java
- **문제 이름**: 가장 긴 바이토닉 부분 수열
- **문제 링크**: https://www.acmicpc.net/problem/11054
12512KB
92ms
LIS를 앞에서부터, 뒤에서부터 두 방향에서 구해주고
두 배열 값의 합의 최댓값을 구해줬습니다.
=> [4월 3주차] 가장 긴 바이토닉 부분 수열 - 이수빈

APR/WEEK4/점프/박재환.java
- **문제 이름**: 점프
- **문제 링크**: https://www.acmicpc.net/problem/1890
DP 로 풀었습니다. 각 칸에서 이동할 수 있는 칸으로 바로 점프 시켜가며 경로를 누적했습니다. 
경로의 개수가 최대 2^63-1 개 이므로 DP 배열을 long 으로 하지 않으면 80% 에서 틀리네요..
다시 long 을 사용하는 습관을..
=> [4월 4주차] 점프 - 박재환

MAY/WEEK2/고층_건물/정한슬.java
- **문제 이름**: 고층 건물
- **문제 링크**: https://www.acmicpc.net/problem/1027
* 건물 A와 B 사이에서 보이는 건물 수를 카운팅하는 방법
1. 기울기 = (By - Ah) / (Bx - Ax) = a 를 구한다.
2. y = a * (x - Ax) + Bx 기울기를 구한 것을 이용하여 기존 1차 방정식을 만든다.
3. 만일 카운팅 할 빌딩(A ~ B 사이 빌딩)의 높이가 1차 방정식 y값보다 높거나 같으면 그 빌딩 이후는 보이지 않게 된다.
4. idx별로 0 ~ buildingCount, 왼쪽/ 오른쪽을 각각 보이는 빌딩 수를 구하고 max 값 갱신
위의 로직으로 풀었습니당. 뭔가 문제 보자마자 기울기, 1차 방정식으로 풀고싶어서 이 문제 먼저 풀었어욤
그리고 왜 다시 보일 때 count++만으로도 가능한지 이해를 못했는데, 
* idx:      0   1   2   3   4
* height:   1   3   1   4   2
이때 예제를 보고 이해했어요.
수학적으로 접근해놓고 비교할 1차 방정식을 단순하게 y = a * x로 생각하고 기울기도 int로 하고.. 수학적인듯 수학적이지 않은 나의 brain~
=> [5월 2주차] 고층 건물 - 정한슬
